[package]
name = "iconwriter"
version = "0.1.2"
authors = ["Warren Galyen <warrengalyen@users.noreply.github.com>"]
edition = "2018"
description = "A simple solution for generating .ico and .icns icons. The crate also supports png sequences as an output format."
license = "MIT"
license-file = "LICENSE"
repository = "https://github.com/warrengalyen/iconwriter.git"
homepage = "https://github.com/warrengalyen/iconwriter"
readme = "README.md"

[dependencies]
zip = "0.5.8"
png_encode_mini = "0.1.2"
nsvg = "0.5.1"
ico = "0.1.0"
icns = "0.3.1" 